name: Lint SQL
on:   
  workflow_dispatch:
env:
  SQLFLUFF_VERSION: 1.4.5
jobs:
  lint-sql:
    runs-on: ubuntu-20.04
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.9"
      - name: Cache sqlfluff
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: prime-numbers
          key: ${{ runner.os }}-${{ env.SQLFLUFF_VERSION }}
      - name: Install SQLFluff
        run: "pip install sqlfluff==${{ env.SQLFLUFF_VERSION }}"
